### PR TITLE
System Overview- Include Comm from Battery to SW App

### PR DESCRIPTION
**Pull request by markroche92**
Minor update to System Overview so that battery communicates to the application software of smart watch

### CODE REVIEW

**Comment by fgiarett** [comment]
I suppose Ubuntu Touch doesn't make much sense with two user buttons? I don't think we need an OS after all, could be a bare metal application, if it is not too complicated to update it in other parts of the project

**Review by fgiarett — CHANGES_REQUESTED** [review]
I suppose Ubuntu Touch doesn't make much sense with two user buttons? Maybe a generic OS? But I don't think we need an OS after all, could be a bare metal application, if it is not too complicated to update it in other parts of the project.

**Comment by markroche92** [comment]
> I suppose Ubuntu Touch doesn't make much sense with two user buttons? Maybe a generic OS? But I don't think we need an OS after all, could be a bare metal application, if it is not too complicated to update it in other parts of the project.

I agree - I can remove the OS from the diagram. It is not referred to elsewhere

**Comment by markroche92** [comment]
Removed OS

**Pull request merged**
